spring:
  main:
    banner-mode: console
    allow-circular-references: true

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Elina1980.

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        logging.level.org.springframework.web: DEBUG
        logging.level.org.springframework.web.client: DEBUG
        logging.level.org.springframework: DEBUG
        logging.level.org.hibernate.SQL: DEBUG
        logging.level.org.hibernate.type: DEBUG
        dialect: org.hibernate.dialect.MySQL8Dialect

        logging.level.root: DEBUG
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

      properties:
        hibernate:
          SQL: INFO
          type:
            INFO

server:
  port: 8081
