--liquibase formatted sql
--changeset elina:v.0.1.0-ddl splitStatements:false

CREATE SCHEMA IF NOT EXISTS notification_bot;


create table if not exists notification_bot.users
(
    id         bigint primary key,
    user_name  varchar(100) not null,
    first_name varchar(100),
    last_name  varchar(100),
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

create table if not exists notification_bot.notifications
(
    id            bigint generated by default as identity
        constraint currency_data_pk
            primary key,
    user_id       bigint      not null,
    currency_name varchar(10) not null,
    min_threshold decimal(15,2),
    max_threshold decimal(15,2),
    created_at    timestamp default current_timestamp,
    update_at     timestamp default current_timestamp,
    constraint users_notifications_id_fk
        foreign key (user_id) references notification_bot.users (id)
);

-- create or replace function update_timestamp()
--     returns trigger as
-- $$
-- begin
--     new.update_at = current_timestamp;
--     return new;
-- end;
-- $$ language plpgsql;
--
-- create trigger update_timestamp_trigger
--     before update
--     on notifications
--     for each row
-- execute function update_timestamp();

-- # -- Индекс для ускорения поиска по полю user_id
-- # CREATE INDEX idx_notifications_user_id ON notifications (user_id);