# This workflow will build a Java project with Maven,
# and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      #          - name: Setup Docker
      #            run: |
      #                sudo service docker start
      #          - name: build with Maven
      #            run: ./mvnw verify
      #            run: mvn clean verify

      - name: Build without tests
        run: mvn clean install -DskipTests

      - name: Setup Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce


      - name: Run tests
        run: mvn test
        env:
          TESTCONTAINERS_CHECKS_DISABLE: "true"
          TESTCONTAINERS_RYUK_DISABLED: "true"


#    services:
#      # Docker in Docker
#      docker:
#        image: docker:19.03.5-dind
#        options: "--privileged"
#        env:
#          DOCKER_DRIVER: overlay
#          DOCKER_HOST: "tcp://localhost:2375"
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#      - name: Setup Docker
#        run: |
#            sudo service docker start
#      - name: build with Maven
#        run: ./mvnw verify
#        env:
#          DOCKER_HOST: "tcp://localhost:2375"
